import type { Metadata } from "next";

import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { Island_Moments, Roboto_Flex } from "next/font/google";

const island = Island_Moments({ subsets: ["latin"], weight: "400", variable: "--font-island" });
const roboto = Roboto_Flex({ subsets: ["latin"], variable: "--font-roboto" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${island.variable} ${roboto.variable} antialiased`}
      >
        <Header />
        <main className="flex-1 px-0 lg:px-4 py-6 max-w-7xl mx-auto w-full">
          {children}
        </main>
        <Footer />

      </body>
    </html>
  );
}
